### ISSUE TITLE
Add rules documentation link

### ISSUE THREAD

**Issue by aslafy-z** [reviewdog/action-yamllint#2]
See sample implementation at https://github.com/reviewdog/action-eslint/blob/master/entrypoint.sh

See rules documentation at https://yamllint.readthedocs.io/en/stable/rules.html

**Comment by javierjulio** [comment]
This doesn't seem applicable anymore. The action-eslint was long converted to a composite action. Checking an older commit, I can't find what this would be tied too. I'd welcome a PR to link to the YAML Lint rules docs.
